### ISSUE TITLE
Change ProcessRequest to work with a void* as input instead of a string

### ISSUE THREAD

**Issue by mgonnav** [BasicAlgorithm/Protocol-HSM#12]

**Comment by mgonnav** [comment]
@rodp63, @BasicAlgorithm. Esto no se puede implementar a menos que resuelvan sus issues.

**Comment by BasicAlgorithm** [comment]
#18 pull request try to solved this issue.

**Comment by mgonnav** [comment]
@BasicAlgorithm Please don't solve issues that were **already assigned** to other collaborators. I also implemented this yesterday, I simply didn't make the PR just yet.
