### ISSUE TITLE
Implement function to parse a struct to a char buffer, ready to be sent

### ISSUE THREAD

**Issue by mgonnav** [BasicAlgorithm/Protocol-HSM#16]
For example, if we are the client and want to send a ClientRequest structure to the server, we need a function (e.g. ClientRequest::parseToCharBuffer()) which returns a buffer that can be sent over the network in the format specified by the protocol, i.e., if we have the following ClientRequest:

```c++
LoginRequest req;
req.tam_user = 7;
req.tam_passwd = 4;
req.user = "joaquin";
req.passwd = "gaaa";
```

Then req.parseToCharBuffer() should return "l0704joaquingaaa".

**Comment by mgonnav** [comment]
Idea: It should be a virtual function in the ClientRequest that is implemented differently in each Request structure. We will need the same function implemented for the Response structures.

**Comment by BasicAlgorithm** [comment]
#18 pull request try to solved this issue.

**Comment by mgonnav** [comment]
To close this issue, ALL structures must have this functionality implemented.

**Comment by mgonnav** [comment]
Implement ParseToCharBuffer for all Requests and Responses
- [x] Requests 
- [ ] Responses

**Comment by BasicAlgorithm** [comment]
Implemented

**Comment by mgonnav** [comment]
@BasicAlgorithm Implemented where? Please reference the PR
