### ISSUE TITLE
Implement Send() method

### ISSUE THREAD

**Issue by mgonnav** [BasicAlgorithm/Protocol-HSM#17]
The Send method should be able to send Requests or Responses (they are both sent as char buffers anyway). This is to be implemented after #16 is completed.

**Comment by BasicAlgorithm** [comment]
#18 pull request try to solved this issue.

**Comment by mgonnav** [comment]
SendRequest shall be changed to a more general `Send` function that sends Requests or Responses indistinctively. 
https://github.com/BasicAlgorithm/Protocol-HSM/blob/eeaa2688d846935307dbfdb2e6797ea8f5bb497f/src/main.cpp#L28

Also, the IP and Port in lines 36, 46
https://github.com/BasicAlgorithm/Protocol-HSM/blob/eeaa2688d846935307dbfdb2e6797ea8f5bb497f/src/main.cpp#L36-L46
should be changed to variables.

**Comment by BasicAlgorithm** [comment]
Implemented
