### ISSUE TITLE
Use recv & send instead of read & write

### ISSUE THREAD

**Issue by mgonnav** [BasicAlgorithm/Protocol-HSM#21]
`recv` & `send` are more specific to socket file descriptors, therefore are better suited for this project. All `read` & `write` uses shall be changed for `recv` & `send` respectivelly. The functionality should remain unaffected.

**Comment by BasicAlgorithm** [comment]
ok. by the way, I can't find read & write...  recvfrom and sendto, yes.

**Comment by BasicAlgorithm** [comment]
Solved
