### ISSUE TITLE
Implement threads for client.cpp and server.cpp

### ISSUE THREAD

**Issue by BasicAlgorithm** [BasicAlgorithm/Protocol-HSM#24]
- Two threads. (1st) for CreateRequest and (2nd) for ProcessResponse(int connectionFD)

**Comment by mgonnav** [comment]
On the server:
- Listens on a port waiting for connections. When a connection arrives, launch a thread for that connection that waits for requests and processes them.

On the client:
- Once the connection goes through, creates a thread that waits for responses from the server.
