### ISSUE TITLE
Fix exit and message request

### ISSUE THREAD

**Issue by rodp63** [BasicAlgorithm/Protocol-HSM#36]
- [x] Fix the segmentation fault when sending an exit request.
- [x] When sending a message, sometimes the first character is missing in the response.

**Comment by BasicAlgorithm** [comment]
Solved on https://github.com/BasicAlgorithm/Protocol-HSM/pull/34/commits/fd931d4c7d9281aa08cfdab17b4d214dc8dea30d

**Comment by BasicAlgorithm** [comment]
Confirm and close issue pls
