### ISSUE TITLE
Broadcast & UploadFile structures not implemented.

### ISSUE THREAD

**Issue by mgonnav** [BasicAlgorithm/Protocol-HSM#5]

**Comment by BasicAlgorithm** [comment]
Implemented and waiting for approved pr

**Comment by BasicAlgorithm** [comment]
> _No description provided._
Implemented and waiting for approved pr

**Comment by BasicAlgorithm** [comment]
> _No description provided._

`

**Comment by mgonnav** [comment]
Just for the sake of documentation, this is the related PR #8
